### ISSUE TITLE
Improvement: No view definition found

### ISSUE THREAD

**Issue by leckylao** [rails-sqlserver/activerecord-sqlserver-adapter#274]
Got this message today.

TinyTds::Error: There is no text for object 'MSP_AGREE_VIEW'.: EXEC sp_helptext [MSP_AGREE_VIEW]
No view definition found, possible permissions problem.
Please run GRANT VIEW DEFINITION TO your_user;
(Object doesn't support #inspect)

But as the great corporate enterprise security rule only grant me select permission. So I found an alternative way, which using 'sp_columns' instead of 'sp_helptext'. I think it's a good improvement keep the same functionality and also avoid the permission issue like this.

**Comment by jdlam** [comment]
How do you tell TinyTds to use 'sp_columns' instead of 'sp_helptext'?

I'm currently having a similar issue, trying to load data from a sql server, but every time I connect to the db and use '.all' on my model, it gives me an error saying I don't have permissions. I know I have permissions since I'm using the same username and password to view the data within WinSQL.

**Comment by jdlam** [comment]
Thanks for reopening this, but I actually found the line of code that needed to be changed.

You can workaround this issue if you go into your gems with the path `vendor/bundle/ruby/2.2.0/gems/sic-activerecord-sqlserver-adapter-4.0.0/active_record/connection_adapters/sqlserver` and open the `schema_statements.rb` file

On line 335, replace `sp_helptext` with `sp_columns` as a hotfix to this issue.

**Comment by ZiaMM** [comment]
That hotfix from @jdlam generates a different issue in my case, using version 3.2.12 - "SHOWPLAN permission denied in database <dbnamehere>' ".  
As with the other posters, I can read the table and all data OK using MS SQL Server tools, with the same user/pass.  
Do we know what query method MS-SQL-Tools use, so that we can substitute it's call for these others that require additional permissions?

**Comment by metaskills** [comment]
Remember, this issue's core is about not having permission to execute `sp_helptext`. The error generated says that the fix is to call `GRANT VIEW DEFINITION TO` your user. If this is simply not an option, the proposal is to use `sb_columns`.

* `sp_columns` - https://msdn.microsoft.com/en-us/library/ms176077.aspx
* `sp_helptext` - https://msdn.microsoft.com/en-us/library/ms176112.aspx

These backup procedures are used when the view definition is over 4000 chars long and can not fit in the information schema representation. Basically, I think we are mostly just looking for the table name the view uses when we reflect on the models columns. Our test for one aspect of this looks something like this.

```ruby
select_values("EXEC sp_helptext [sst_string_defaults_big_view]", 'SCHEMA')
```

Which returns a nice big string of the actual view that we can grep for and try to figure out the table name. Using `sb_columns` is not a drop in replacement. It is a different philosophy and set of info returned. 

```ruby
r = select_all("EXEC sp_columns [sst_string_defaults_big_view]", 'SCHEMA')
r = ActiveRecord::Result.new r.columns, r.rows
r.each { |x| pp(x) }
{"TABLE_QUALIFIER"=>"activerecord_unittest",
 "TABLE_OWNER"=>"dbo",
 "TABLE_NAME"=>"sst_string_defaults_big_view",
 "COLUMN_NAME"=>"id",
 "DATA_TYPE"=>4,
 "TYPE_NAME"=>"int identity",
 "PRECISION"=>10,
 "LENGTH"=>4,
 "SCALE"=>0,
 "RADIX"=>10,
 "NULLABLE"=>0,
 "REMARKS"=>nil,
 "COLUMN_DEF"=>nil,
 "SQL_DATA_TYPE"=>4,
 "SQL_DATETIME_SUB"=>nil,
 "CHAR_OCTET_LENGTH"=>nil,
 "ORDINAL_POSITION"=>1,
 "IS_NULLABLE"=>"NO",
 "SS_DATA_TYPE"=>56}
{"TABLE_QUALIFIER"=>"activerecord_unittest",
 "TABLE_OWNER"=>"dbo",
 "TABLE_NAME"=>"sst_string_defaults_big_view",
 "COLUMN_NAME"=>"pretend_null",
 "DATA_TYPE"=>-9,
 "TYPE_NAME"=>"nvarchar",
 "PRECISION"=>4000,
 "LENGTH"=>8000,
 "SCALE"=>nil,
 "RADIX"=>nil,
 "NULLABLE"=>1,
 "REMARKS"=>nil,
 "COLUMN_DEF"=>nil,
 "SQL_DATA_TYPE"=>-9,
 "SQL_DATETIME_SUB"=>nil,
 "CHAR_OCTET_LENGTH"=>8000,
 "ORDINAL_POSITION"=>2,
 "IS_NULLABLE"=>"YES",
 "SS_DATA_TYPE"=>39}
```

This data is highly valuable. However!!! It just shows that this is not a drop in replacement. As is now our `column_definitions` method does just fine finding this information using `INFORMATION_SCHEMA`. What we need when eventually call down to `sp_helptext` is the TABLE NAME the view is referencing. In this example, I see now hint of `sst_string_defaults` table name.

So we have to define what we are trying to fix. When we recommend things like `sb_columns` I see that as an alternative to all the hard work the `columns_definitions` is doing. And from what I see, it does not do it well. I can't even see column defaults which is one of the primary reasons we use `INFORMATION_SCHEMA`. I'm open to ideas, but I don't see any work here that I can do.
