### ISSUE TITLE
Finding default order from a view fails trying to access Arel::Table#columns

### ISSUE THREAD

**Issue by nickveys** [rails-sqlserver/activerecord-sqlserver-adapter#358]
[Arel::Table#columns has been removed since 3.0](https://github.com/rails/arel/issues/65).  Active Record 4.1 depends on ~> 5.0.0, so it is long gone.  This causes a failure when trying to to call Arel::Visitors::SQLServer#rowtable_orders when querying a view with no `order` statements.  It ultimately tries to call `#columns`, failing since the method does not exist.

    NoMethodError: undefined method `columns' for #<Arel::Table:0x00000118a82d70>
    from ../lib/arel/visitors/sqlserver.rb:439:in `rowtable_orders'

Note that this happens when a `SELECT TOP (X)` query is built, such as when using `will_paginate`, where order becomes important whether its specified in the query or not.  We can work around this by specifying a default order but using a removed method seems like a recipe for future failures.

**Comment by jwoertink** [comment]
Weird thing is that I just deployed an app to 2 different servers. Both are using the same codebase, but set up slightly different. I get this same error on one server, but not the other.

It seems to happen when calling `page()` from kaminari for me. Just odd that I'm using the same version of this gem and kaminari on both environments. I think the SQL version is different though because one is express and the other is on Azure.

```text
irb(main):004:0> Appointment.where(directoryid: nil).to_sql
=> "SELECT [Appointment].* FROM [Appointment] WHERE [Appointment].[directoryid] IS NULL"
irb(main):005:0> Appointment.where(directoryid: nil).page(1).to_sql
NoMethodError: undefined method `columns' for #<Arel::Table:0xbab737c4>
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.1.0/lib/arel/visitors/sqlserver.rb:433:in `rowtable_orders'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.1.0/lib/arel/visitors/sqlserver.rb:161:in `visit_Arel_Nodes_SelectStatementWithOffset'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.1.0/lib/arel/visitors/sqlserver.rb:13:in `visit_Arel_Nodes_SelectStatement'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:22:in `visit'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:5:in `accept'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation.rb:528:in `to_sql'
	from (irb):5
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/app_rails_loader.rb:43:in `require'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/app_rails_loader.rb:43:in `block in exec_app_rails'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/app_rails_loader.rb:32:in `loop'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/app_rails_loader.rb:32:in `exec_app_rails'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/cli.rb:5:in `<top (required)>'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/bin/rails:9:in `require'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/bin/rails:9:in `<top (required)>'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/bin/rails:23:in `load'
	from /home/deploy/ard-checkin/shared/bundle/ruby/2.1.0/bin/rails:23:in `<main>'irb(main):006:0> 
```

**Comment by jwoertink** [comment]
Just to add some more info to this. I have my app running in 3 environments, 2 of which work fine, but the third I get this error:

Development running locally works.
```text
Microsoft SQL Server 2012 - 11.0.2218.0 (X64) 
	Jun 12 2012 13:05:25 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```
Production running on Azure works.
```text
Microsoft SQL Azure (RTM) - 11.0.9229.22 
	Jan 19 2015 17:56:57 
	Copyright (c) Microsoft Corporation
```

Production running on a virtual box local pc fails.
```text
Microsoft SQL Server 2012 (SP1) - 11.0.3128.0 (Intel X86) 
	Dec 28 2012 19:06:41 
	Copyright (c) Microsoft Corporation
	Standard Edition on Windows NT 6.2 <X64> (Build 9200: ) (WOW64)
```

Rails Version - `4.1.8`
Ruby Version - `2.1.5`
TinyTds Version - `0.6.2`
Kaminari Version - `0.16.1`
FreeTDS Version - `0.91`

**Comment by metaskills** [comment]
I want to close this issue because this is likely solved in 4.2.

**Comment by jwoertink** [comment]
I'm actually testing that right now with the 4.2.0.pre. That should include all latest changes, right?

**Comment by jwoertink** [comment]
whoa! sweet! Ok, so I tested on my wonky machine and locally, and they both work! Even better yet is the query generated looks WAY more readable. I haven't pushed to Azure yet, but I'll assume that will work too.

**Comment by raphox** [comment]
@metaskills Do you know which commits fixed this?

**Comment by metaskills** [comment]
@raphox Not really, Rails 4.2 and by that the adapter, was a huge change internally. A lot of things changed since 4.1... even more so for 3.x.

**Comment by mwlang** [comment]
It's bombing in 4.1.1 because, for whatever reason t.primary_key and t.columns are both nil in this method:
~~~ruby
module Arel
  module Visitors
    class SQLServer
      def rowtable_orders(o)
        if !o.orders.empty?
          o.orders
        else
          t = table_from_select_statement(o)
          c = t.primary_key || t.columns.first
          [c.asc]
        end.uniq
      end
  end
end
~~~
When the table's Column#is_primary? is false even if 'self.primary_key = some_column' is present in the Model's definition.  I was able to resolve this with the following monkey_patch:

Set the is_primary flag to true o the column when self.primary_key= is called on the model:

~~~ruby
module ActiveRecord
  module AttributeMethods
    module PrimaryKey
      protected
      module ClassMethods
        def primary_key=(value)
          @primary_key        = value && value.to_s
          @quoted_primary_key = nil
          columns.each{|c| c.is_primary = c.name == @primary_key} # added!
        end
      end
    end
  end
end
~~~
Then implement def is_primary=(value) on SQLServerColumn:
~~~ruby
module ActiveRecord
  module ConnectionAdapters
    class SQLServerColumn
      def is_primary=(value)
        @sqlserver_options[:is_primary] = value
      end
    end
  end
end
~~~
I put both of these in my Rails project's config/initializer/monkey_patches.rb and it resolved the above issue.

**Comment by metaskills** [comment]
I looked at the patches suggested and I can not include these since they patch ActiveRecord too. I am going to close this issue with a few recommendations.

* Make sure you can run `sb_helptext` procedure for your app's user. This is what is used to pull back good schema reflection for views and a lack of user permissions to execute that proc will likely result in a lack of primary key being set.
* If you absolutely need to freedom patch the column objects. May I suggest you do it this way.

```ruby
MyModel.columns_hash['mypk'].instance_variable_get(:@sqlserver_options)[:is_primary] = true
```
