### ISSUE TITLE
simple_form not happy with varchar

### ISSUE THREAD

**Issue by kwerle** [rails-sqlserver/activerecord-sqlserver-adapter#411]
I don't know that this is anyone's bug, but I was disappointed that simple_form didn't work with varchar fields after I upgraded the adapter.
I believe that varchar's used to map to 'string', but now map to 'varchar'.  I ended up with simple_form complaining that it didn't know how to handle input for varchar ("No input found for varchar" - backtrace to simple_form/form_builder.rb:574).

I bring this up, here, because I figure it's worth discussion - and my guess is a lot more folks use simple_form than this adapter.

**Comment by metaskills** [comment]
Thanks @kwerle, this is a good topic. I have not used [simple_form](https://github.com/plataformatec/simple_form) before. I did a quick search on their repo and found this issue. https://github.com/plataformatec/simple_form/issues/1241 What are your thoughts on using that feature?

**Comment by metaskills** [comment]
I also made a comment in that issue with this example:

```ruby
# SQL Server Adapter
map_type :ntext, :varchar_max, :nvarchar_max,    to: SimpleForm::Inputs::TextInput
map_type :char, :nchar, :varchar,                to: SimpleForm::Inputs::StringInput
map_type :bigint, :real, :smallmoney, :money,    to: SimpleForm::Inputs::NumericInput
```

**Comment by kwerle** [comment]
Yeah, if you think this is a shortcoming of SimpleForm and not a 'too-verbose' list of column type mappings in the adapter, then I'm willing to buy into that.  Comment added to SimpleForm.

**Comment by kwerle** [comment]
One of the things that's nice about rails is that the same schema.rb can be used for many different databases.  The schema.rb that this gem generates from a database will not work with other databases for the same reason it won't work with simple_form.  That's why I wonder if the issue isn't with the adapter instead of simple_form.

**Comment by metaskills** [comment]
> One of the things that's nice about rails is that the same schema.rb can be used for many different databases.

I'm not sure this is entirely ture. It used to be a by-product design back in the day when all Rails handled was simplified types. As each adapter gets better at handling their own data types, like this one has, then the contract (if even true) can not be maintained. For example, doesn't PostgreSQL has many data types which is support in Rails core that can not be used by other DBs in schema.rb?
 
I think schema.rb is a way to represent your current database, not a homogenized cross DB view. If the later were true, it would really hurt adapters like this adding value to the practices setup by Rails to do `db:setup` and `db:test:prepare`. This adapters datatypes are not added willy nilly, they are added there to ensure that when you use the schema.rb and clone the structure you get the exact data types. In our case that could be a `:string` of column type `varchar` vs `nvarchar` because you may have tests based on that type.

The point could be made that schema.rb is meant to be DB agnostic and those truly needing specific DB should use the `:sql` schema format? 

PING @tenderlove @sgrif for thoughts?

**Comment by kwerle** [comment]
Unhappily, I have been living outside the postgres world for a while.  My hope was that schema.rb would continue to be mostly cross-database compatible and the more extravagant (database-specific) options would live in the option hash.

**Comment by metaskills** [comment]
OK, I think I got this wrong. I did some searching on advanced PostgreSQL features and came up with a few articles that state that you always have to use the `:sql` schema format when using them. I also found that the [Rails Guides - Schema Dumping and You](http://edgeguides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you) mentions:

> This file is created by inspecting the database and expressing its structure using create_table, add_index, and so on. Because this is database-independent, it could be loaded into any database that Active Record supports. This could be very useful if you were to distribute an application that is able to run against multiple databases.

The statement **any database that Active Record supports** is very clear there. Now that this 4.2 adapter has good structure dump support using FreeTDS' `defncopy` binary AND we are only a few steps away from providing these binaries in the Windows build... I am going to fix this in our 4-2-stable branch. Give me a week or so and thanks for the discourse!

**Comment by kwerle** [comment]
Thank you.  The 4.2 adapter is certainly a huge step up from 4.1.  If there is anything I can do to help, please let me know.

**Comment by sgrif** [comment]
FWIW in practice I think the main benefit of `schema.rb` is considered to be that merge conflicts are way easier.

**Comment by metaskills** [comment]
Whoops, looks like I was right all along and those docs are out of date. I did a simple test in a demo app that has PostgreSQL for the primary connection. See here for the addition of a `macaddr` type. https://github.com/customink/encom_dbs/commit/2dd5b34967d0c4626fdcd4b1e393354cabdb0d89

As that commit shows, since the PG adapter implements the non simplified types just like we do – the schema dumper does exactly as we do too. In fact, it even doubles down on that by introducing a method in the schema dumper called `enable_extension`. I even found a few tests for these types.

* [PG's Custom Schema Definitions](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_definitions.rb#L4-L90)
* [PG's Custom Schema Definition Tests](https://github.com/rails/rails/blob/4-2-stable/activerecord/test/caseting up s/schema_dumper_test.rb#L252-L349)

Based on this, I think the proper fix is in the simple_form gem, local patches, or even homogenizing your production schema. If you are off the simplified type reservation, and SQL Server's national string types push you this way, then you will need to make adjustments to cope with that. Hope this was helping... any closing thoughts?

**Comment by kwerle** [comment]
Yeah, that's not real surprising - but still a little disappointing.  Thanks for all your investigation and research.
