### ISSUE TITLE
Support for hstore type

### ISSUE THREAD

**Issue by muichkine** [rails-sqlserver/activerecord-sqlserver-adapter#422]
Hello,
Is there planned support for equivalent of PostgreSQL's :hstore data type?

Running a migration to enable hstore seems to work on SQL Azure V12:

    class EnableHstoreExtension < ActiveRecord::Migration
      def change
        enable_extension 'hstore'
      end
    end

but creating a hstore column fails:

    add_column      :contacts, :auxiliaries, :hstore

yields

    TinyTds::Error: Column, parameter, or variable #18: Cannot find data type hstore.: ALTER TABLE [contacts] ADD [auxiliaries] hstore/home/avril14th/.rvm/gems/ruby-2.2.3/gems/activerecord-sqlserver-adapter-4.2.4/lib/active_record/connection_adapters/sqlserver/database_statements.rb:284:in `do'

Thanks. :)

**Comment by metaskills** [comment]
Yes there is! That should be coming in the next few weeks.

**Comment by muichkine** [comment]
Is there any way I can help on this? I am migrating from PostgreSQL and I need this to get going asap.  :)

This would be darn cool. Thanks.

**Comment by metaskills** [comment]
Sure! Especially if you do not mind opening a pull request and doing some back and forth reviews/ideas with me. Since SQL Server really just uses a nvarchar type, we would subclass our type for that and add it in a few places.

**Comment by muichkine** [comment]
OK, I'll start by browsing the code a bit see if I can find an entry point for a pull.

BTW: SQL Azure supports indexing hstore keys right? :)

**Comment by metaskills** [comment]
It does... which would be the same for the 2016 box product too. Using a nvarchar type allowed Microsoft to put the emphasis on the query and indexing of the store. Later it will be a true native type. Their thinking was that people are already using JSON in nvarchar columns, so they will be able to migrate easily. Bonus on our side is we just don't care. The downsides is that we have to come up with some sort of mechanism for users to declare this type in their model since there is not underlying column hints.

**Comment by muichkine** [comment]
OK cool. Think I got the general idea. Thanks

**Comment by metaskills** [comment]
Some reading for myself http://www.databasejournal.com/features/mssql/getting-started-with-json-support-in-sql-server-2016-part-1.html

**Comment by muichkine** [comment]
Looks great. Is Azure already running SQL 2016?

**Comment by metaskills** [comment]
I am not sure there is any work to do here. Since there is no SQL Server datatype/column for JSON, and all the logic is in the queries. So Rails should be able to use conventions like [ActiveRecord::Store](http://api.rubyonrails.org/classes/ActiveRecord/Store.html) and people can make scopes that use the TSQL JSON functions as needed. More reading here. https://msdn.microsoft.com/en-us/library/dn921897.aspx
