### ISSUE TITLE
Server name not found in configuration files

### ISSUE THREAD

**Issue by wissil** [rails-sqlserver/activerecord-sqlserver-adapter#500]
I keep seeing this error, and I am unable to connect to the database on the remote server.
I was given a connection string to the database, that looks like the following:

`data source=qsss.gar.de\SQL2012,3000;initial catalog=City;persist security info=True;user id=user_me;password=user_me##2009;`

I have created a `database.yml` file based on that connection string, like the following:
`development:
 adapter: 'sqlserver'
 host: 'qsss.gar.de\SQL2012,3000'
 port: 1433
 database: 'City'
 username: 'user_me'
 password: 'user_me##2009'`

And as I try and run the server, it always hits me with the **Server name not found in configuration files** error.

```
` opts[:port] ||= 1433
      opts[:dataserver] = "#{opts[:host]}:#{opts[:port]}" if opts[:dataserver].to_s.empty?
      connect(opts) // ERROR AT THIS LINE
    end

    def tds_73?`
```

Please try and help me figure what is the problem with this?

**Comment by metaskills** [comment]
Hey there. You can not use the settings form the connection string as a 1-1 yaml mapping. I think the problem is with your `host` being a named instance and I have no idea what that `3000`... assuming a port? If so, then you r`port` setting is wrong. I suggest first testing a connection in IRB with TinyTDS using this info and then moving from there. https://github.com/rails-sqlserver/tiny_tds#tinytdsclient-usage
