### ISSUE TITLE
Rails 5, connect to SQL Server 2008

### ISSUE THREAD

**Issue by nkabbara** [rails-sqlserver/activerecord-sqlserver-adapter#571]
Hello,

We were about to upgrade to rails 5 and noticed that we'd have to upgrade this gem to 5 as well, which doesn't seem to be compatible with SQL Server 2008 (docs say 2012 or later).

How would one would proceed with this situation?

**Comment by metaskills** [comment]
> which doesn't seem to be compatible with SQL Server 2008

That is correct.

> How would one would proceed with this situation?

That would vary greatly depending on your situation. Version 4.2 and upward only support 2012 and higher. A large part of that decision was due to the incredible pain points of support ActiveRecord's LIMIT & OFFSET support. Because 2012 has FETCH, this drastically simplified our ability to keep moving forward and supporting Rails. What does this mean for you? Again, there are numerous choices on who you are, what your app does, and what is important for you.

* Upgrade your DB to 2012.
* Stay at Rails 4.1 till you upgrade your DB.
* Fork the adapter and hack the Arel visitor as needed. 

Please note that the 3rd option is something that is a) never going to make its way back into the adapter and that b) is no small task. Please search the issue for a few other topics where we have talked about this. Hope that is helpful and I've given you enough information to help. Cheers.
