### ISSUE TITLE
Any plans for enabling SQL 2016 Temporal Tables

### ISSUE THREAD

**Issue by ThorkilG12** [rails-sqlserver/activerecord-sqlserver-adapter#584]
Then one would have Type-2 history on tables for free  :-)

**Comment by metaskills** [comment]
Cool... can you explain how this would be a concern of ActiveRecord and/or the adapter and what we can do? For example, since `create_table` allows specific DB `options:` you can pass those strings as needed and make temporal tables now right?. See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/573 on how I exemplified in-memory tables using the same built-in ActiveRecord interface.

**Comment by ThorkilG12** [comment]
I'm not quite sure what you talk about here...
It's amazing how difficult is is to get under the hood of the way you talk
within these GIT things...
Compared to all the technical manuals and sys-admin stuff I hvae read
about, you guys take the prize  :-)

Anyway... To make RoR to create and use Temporal tables... My guess is that
it is an easy task (for you guys  :-))

Here is my short intro: http://www.g12.dk/nomenu/temporal

If I can tell the adapter that I want a Temporal Table, then all "the
usual" CRUD that poeple knows within RoR will act as normal.
But... If I want to... I will have new possibilities... If the adapter let
med pass the "FOR SYSTEM TIME" syntax over til the MS SQL Server

Hm... It's over midnight... I'm not very satisfied with this mail... It's
what I'm able to at this time... Sorry

Have a nice day

/T

*Venlig hilsen*

*Thorkil Johansen*
*Tel: +45 4070 6547*


2017-04-26 2:22 GMT+02:00 Ken Collins <notifications@github.com>:

**Comment by metaskills** [comment]
Let me be more terse. I think you have what you need already using ActiveRecord's `options` to the `create_table` method. For example:

```ruby
create_table :users, options: 'WITH (SYSTEM_VERSIONING = ON) ' do |t|
  t.string :email
  t.timestamps
end
```

**Comment by metaskills** [comment]
OK, I just got finished with the Rails v5.1 work in master to get our new gem support out and rounding back to a few old issues. I have not seen a reply here so I am going to assume you can use the `options` to `create_table`. If that is not the case or you need help, please reach out. Just because the ticket is closed does not mean the conversation is :) cheers.
