### ISSUE TITLE
How to make things failsafe

### ISSUE THREAD

**Issue by sookcha** [rails-sqlserver/activerecord-sqlserver-adapter#630]
I want to make things failsafe.

If the database server is down, or something goes wrong, TinyTds throws `TinyTds::Error`. But I can't catch that error. All I want to do is to write log for that and show an error page for user.

I've searched long time but I can't find how.

**Comment by metaskills** [comment]
Not sure something this complex can be answered in a GitHub issue/chat. Failsafe is going to depending highly on what you are doing. For example, if ActiveRecord objects were accessed in a ActiveJob queue like Sidekiq, then failsaved is already ensured by the job being rescheduled. However, fail safety for a DB on an application level is only understood by knowing that app well. Most apps can not work without the DB and that is just fine and logical. Hence, we call the DB a tier 1 dependency. 

That said, you have a few options if you all you want to do is simply log things. Application services like NewRelic, and Rollbar handle this for you. Have you considered those?

> TinyTds throws TinyTds::Error. But I can't catch that error

Correct... ActiveRecord (properly) does not expose the low level connection errors. They are all wrapped https://github.com/rails/rails/blob/master/activerecord/lib/active_record/errors.rb and the base one is `ActiveRecord:: StatementInvalid` but if you read some Rails code and docs, I think you might find something that says your never supposed to rescue that because it will keep ActiveRecord from doing proper error handling, like wrapping other common exceptions. Instead your supposed to only rescue what you expect. 

Are you doing this at the controller level? Have you considered using `rescue_from` on something like `ActiveRecord::ActiveRecordError` or something? To be honest, I would just use New Relic, Rollbar, or the like.
