### ISSUE TITLE
Rails 6

### ISSUE THREAD

**Issue by m-andreas** [rails-sqlserver/activerecord-sqlserver-adapter#683]
As rails 6 Beta is out, are there any plans for rails 6 already?

**Comment by wpolicarpo** [comment]
Not yet. PRs are welcome now that 5.2.0 was released.

**Comment by wpolicarpo** [comment]
For those willing to help, #690 is waiting for some contributors.

**Comment by juice** [comment]
Rails 6.0 is released.

**Comment by net1957** [comment]
I'm trying to update to rails 6 and hit this problem.

Seems to turn around @columns_hash. Some code did change in AR.
Have you an idea on the time frame needed to modify this great code ?

Can I help on some aspects ?
Regards

**Comment by spacerobotTR** [comment]
Is a rails 6.0 release being worked on still?

**Comment by ttilberg** [comment]
@wpolicarpo You have a branch linked above that was a draft for Rails 6 wip, so you seem to have some experience working on the adapter. Can you provide some public insight about what kind of changes happened to AR that make SQL Server hard to support? I'm not trying to pin you down specifically, it's just that there's been a lot of stalled progress on both TinyTDS and AR Adapter. It has me wondering what challenges have been presented (and ultimately, whether it's anything I can help make progress against). Thanks!

**Comment by dglaser** [comment]
@ttilberg The "Rails 6 wip" branch has not merged any pull requests. I believe my pull request ( #714 ) is the latest. This PR includes:
- #710 - changed the parameters for `sql_for_insert` method to match changes to active-record
- I changed the rails version to 6.0.0 from 6.0.0.beta3

These small changes cleared up a lot of the failing tests and errors. Unfortunately, there are still failing tests due to one of two issues:

1. `ActiveRecord::StatementInvalid: TinyTds::Error: Cannot insert explicit value for identity column in table 'posts' when IDENTITY_INSERT is set to OFF.`
2. `ActiveRecord::ConnectionNotEstablished: No connection pool with 'primary' found.`

**Comment by ttilberg** [comment]
@dglaser I've found something relevant to the 1st note -- I added a pr to yours.

**Comment by johan-smits** [comment]
Meanwhile this support is in progress are there alternatives?

**Comment by wpolicarpo** [comment]
Hey guys, unfortunately there are no alternatives, except to help with the migration :(

I released v5.2.1 yesterday and master is green-ish again (thanks to @aidanharan) so we can focus on Rails 6 in #690 as I already mentioned.

**Comment by johan-smits** [comment]
@wpolicarpo I ended up downgrading my rails setup because the app was simple.

I don't have enough experience to help with the migration but will track the status of this issue when there are test users needed.

**Comment by JesseChavez** [comment]
@johan-smits and @all If you guys don't mind [JRuby ](https://github.com/jruby/jruby) there is already an alternative SQL Server adapter since last year.

* [gem](https://rubygems.org/gems/activerecord-jdbc-alt-adapter)
* [repo](https://github.com/JesseChavez/activerecord-jdbc-adapter)
* basic sample app you can use as guide [wombat](https://github.com/JesseChavez/wombat60)

bear in mind it only works in JRuby.

**Comment by matthewdunbar** [comment]
Thanks for all the work you all have done upgrading to Rails 6. I upgraded using the 6-0-dev branch about a week ago and haven't run into any kind of significant issues.

**Comment by tbonz** [comment]
It's been awesome to follow the progress made over the past months.  Great to see 6.0.0rc1 out there now!  Nice work!

**Comment by wpolicarpo** [comment]
Hi guys, version [6.0.0.rc1](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/CHANGELOG.md) is out.

Please test and report any issues you may find.

Closing this.

**Comment by johan-smits** [comment]
@JesseChavez to me it is looking good! Thanks for the effort of all the contributors!

**Comment by net1957** [comment]
rc2 is working for me on Rails 6.0.3.1
Thanks for this!
