### ISSUE TITLE
Clarify `timeout` parameters and difference with TinyTDS

### ISSUE THREAD

**Issue by OmriSama** [rails-sqlserver/activerecord-sqlserver-adapter#959]
Hello. I wanted to ask for some clarification on `timeout`s and the relationship between the adapter, TinyTDS, and FreeTDS.

1. I've been trying to figure out if the FreeTDS `timeout` parameter is in seconds, or something else. The documentation doesn't clarify this: https://www.freetds.org/userguide/freetdsconf.html
2. TinyTDS says it's in seconds in the README; cool.
3. I look at the `activerecord-sqlserver-adapter` code and it divides whatever the `timeout` is by `1000`. Is this to maintain compatibility with other ActiveRecord Adapters that expect timeout to be in milliseconds?

TIA

**Comment by aidanharan** [comment]
If you run `man freetds.conf` (https://www.systutorials.com/docs/linux/man/5-freetds/) it documents the timeout as being in seconds. As you said TinyTDS also uses seconds. And since other ActiveRecord adapters use milliseconds it is necessary for the SQL Server adapter to convert milliseconds to seconds before passing it to TinyTDS.

- SQL Server Adapter: Milliseconds
- TinyTDS: Seconds
- FreeTDS: Seconds
